---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow:
    collect:
      metrics:
        /intel/psutil/cpu/cpu-total/user: {}
        /intel/psutil/cpu/cpu-total/system: {}
        /intel/psutil/cpu/cpu-total/idle: {}
        /intel/psutil/load/*: {}
      publish:
        - plugin_name: "file"
          config:
            file: "/tmp/psutil_metrics.log"
